title: Your Name
description: Research in state estimation & SDEs
url: https://KarlHammar.github.io
baseurl: ""            # set to "/REPO" for project pages
plugins:
  - jekyll-remote-theme
remote_theme: poole/lanyon
